Mapa mental
UnBArqDsw2020-2/2020.2_G1_CabeleleiraLeila pull request #16
Opened 2021-02-11 23:33 UTC by RafaellaJunqueira

closes #6 

### Tarefas realizadas
- Algumas correções no documento do Design Sprint
- Inclusão do Mapa Mental

2021-02-12 12:05 UTC, ErickGiffoni commented
O pull request não seria primeiro para a branch gh-pages ?

2021-02-15 15:22 UTC, ErickGiffoni requested changes

2021-02-15 15:22 UTC, ErickGiffoni commented on docs/base/brainstorming.md
>  |1 | O usuário deve ser capaz de realizar o login|
esses números não iam ficar como BS<número> ?

2021-02-15 15:22 UTC, ErickGiffoni commented on docs/base/design-sprint.md
> +| 10.02.2021 | 0.1 | Criação do documento, adição de metodologia e artefatos desenvolvidos | Rafaella Junqueira |<br>
Acho que pode ser versão 1.0

2021-02-15 15:22 UTC, ErickGiffoni commented on docs/base/mapa-mental.md
> +| 11.02.2021 | 0.2 | Adição do mapa mental | Rafaella Junqueira |<br>
Por que não versão 1.0 ?

2021-02-15 15:22 UTC, ErickGiffoni commented on docs/base/mapa-mental.md
> +O Mapa Mental é uma ferramenta que permite a organização de seu conteúdo de maneira harmônica com os processos cognitivos, ou seja, a disposição dos elementos é feita da mesma forma como ocorre em no
muito bom

2021-02-15 15:22 UTC, ErickGiffoni commented on docs/base/mapa-mental.md
> +![mapa-mental](../img/base/mapa-mental.jpg)
she rocks ! show

2021-02-15 16:26 UTC, RafaellaJunqueira commented on docs/base/design-sprint.md
> +| 10.02.2021 | 0.1 | Criação do documento, adição de metodologia e artefatos desenvolvidos | Rafaella Junqueira |<br>
Esse doc está sendo atualizado em outro branch. Ele vai terminar na versão 1.0 ;)

2021-02-15 16:28 UTC, RafaellaJunqueira commented on docs/base/brainstorming.md
>  |1 | O usuário deve ser capaz de realizar o login|
Bem lembrado, obrigada!

2021-02-15 16:29 UTC, RafaellaJunqueira commented
Modificações realizadas! @ErickGiffoni

2021-02-15 17:18 UTC, merged