Adiciona Diagramas de Atividades
UnBArqDsw2020-2/2020.2_G1_CabeleleiraLeila pull request #65
Opened 2021-02-28 18:49 UTC by damarcones

Co-authored-by: brunaalmeidasantos <brunaalmeida48@gmail.com>
Criação dos Diagramas de Atividades referente a issue #50.

2021-03-01 12:37 UTC, ErickGiffoni requested changes
Sugiro adicionar breves comentários explicando os diagramas, para dar uma consistência maior no documento. No mais, parabéns pelo bom trabalho !

2021-03-01 12:37 UTC, ErickGiffoni commented on docs/modelagem/diagrama_atividades.md
> +| 28.02.2021 | 0.2 | Adição dos Diagramas de Atividades |Bruna Almeida, Damarcones Porto|
Sugiro já deixar versão 1.0 , uma vez que já estamos fazendo esse Pull Request

2021-03-01 12:37 UTC, ErickGiffoni commented on docs/modelagem/diagrama_atividades.md
> +
Sugiro adicionar breves comentários explicando a imagem que foi adicionada (o diagrama)

2021-03-01 12:37 UTC, ErickGiffoni commented on docs/modelagem/diagrama_atividades.md
> +
Sugiro adicionar breves comentários explicando a imagem que foi adicionada (o diagrama)

2021-03-01 12:37 UTC, ErickGiffoni commented on docs/modelagem/diagrama_atividades.md
> +
Sugiro adicionar breves comentários explicando a imagem que foi adicionada (o diagrama)

2021-03-01 12:37 UTC, ErickGiffoni commented on docs/modelagem/diagrama_atividades.md
> +
Sugiro adicionar breves comentários explicando a imagem que foi adicionada (o diagrama)

2021-03-01 16:25 UTC, isabellacgmsa approved these changes
Se possível comentar mais sobre os que foram feitos, no mais ficou ótimo

2021-03-03 12:40 UTC, damarcones commented
Realizada as mudanças solicitadas pelos revisores @ErickGiffoni e @isabellacgmsa referentes a issue #50.

2021-03-03 12:41 UTC, merged